In [7]:
#1. Create a null vector of size 10 but the fifth value which is 1.
import numpy as np
x=np.zeros(10)
x[4]=1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [6]:
#2. Create a vector with values ranging from 10 to 49.
y=np.arange(10,50)
y

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [10]:
#3. Create a 3x3 matrix with values ranging from 0 to 8
x =  np.arange(0,9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
#4. Find indices of non-zero elements from [1,2,0,0,4,0]
import numpy as geek
arr = geek.array([1,2,0,0,4,0])
out_arr = arr[geek.nonzero(arr)]
print ("Output array of non-zero number: ", out_arr)

Output array of non-zero number:  [1 2 4]


In [15]:
#5. Create a 10x10 array with random values and find the minimum and maximum values.
import numpy as np
x = np.random.random((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum value:",xmin,"Maximum Value:",xmax)


Original Array:
[[0.29805148 0.68289868 0.16406849 0.16641234 0.69221529 0.29262457
  0.29178307 0.73992637 0.91745807 0.15430844]
 [0.76302598 0.52237996 0.66938111 0.59080328 0.01718186 0.31816873
  0.86554534 0.86752905 0.29998495 0.15014089]
 [0.83566983 0.23121092 0.92806861 0.33769113 0.05723057 0.08282369
  0.6295955  0.18339565 0.20590868 0.25818357]
 [0.75295151 0.30842402 0.4360891  0.05960217 0.32539543 0.08605076
  0.54201821 0.35442932 0.55800587 0.80617586]
 [0.06134346 0.03891672 0.89972169 0.92827885 0.71701461 0.92391971
  0.05241828 0.18163306 0.50180046 0.35659867]
 [0.74665147 0.78376944 0.26849585 0.854431   0.95859763 0.88535204
  0.8145858  0.41544317 0.30736846 0.27961194]
 [0.91629313 0.77051696 0.90850519 0.19339974 0.49900692 0.55848341
  0.02600405 0.1876868  0.23973848 0.70508482]
 [0.3881773  0.16715381 0.30474943 0.91194427 0.45647871 0.13592176
  0.95193526 0.00162304 0.84001014 0.86484874]
 [0.52463087 0.57930588 0.72249547 0.52817445 0.3062909  0.57400

In [16]:
#6. Create a random vector of size 30 and find the mean value.
Z = np.random.random(10)
m = Z.mean()
print (m)

0.6072382939763885
